import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex w-screen h-screen p-8">
          <main className="relative m-auto h-full w-screen md:w-2/3 xl:w-1/2 md:h-auto p-8 md:rounded-xl md:shadow-xl bg-white">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
